name: beets
base: core18
version: 'git'
summary: music library manager and MusicBrainz tagger
description: |
  Beets is the media library management system for obsessive-compulsive
  music geeks. The purpose of beets is to get your music collection right
  once and for all. It catalogs your collection, automatically improving
  its metadata as it goes. It then provides a bouquet of tools for
  manipulating and accessing your music.

grade: stable
confinement: strict

parts:
  beets:
    plugin: python
    source: .

apps:
  beets:
    command: bin/beet
    plugs:
      - home
      - network
      - pulseaudio
      - removable-media
